### ISSUE TITLE
Missing shebang

### ISSUE THREAD

**Issue by bizzyman** [gawlk/art#2]
Small error at the top of art script prevents it from running where bash is not default system shell. Shebang at top should read `#!` not `#`.

**Comment by gawlk** [comment]
Hi, thanks for your contribution but I'm not sure that I understand your issue.

That's what on top of all my scripts: `#!/usr/bin/env bash`

**Comment by MarinHoc** [comment]
fixed in PR #1[relevant line](https://github.com/gawlk/art/pull/1/files#diff-2c5f64ab07ccb3e410aa97fc09687cc3L1)
